### ISSUE TITLE
API_ENV=?

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/chatgpt-webapp-server#10]
For production what is the value
API_ENV="prod" or API_ENV="production"

**Comment by c0sogi** [comment]
You have to use "prod". If you use a value other than "local", "test", or "prod", it will automatically fall back to "local".

**Comment by Torhamilton** [comment]
Let's add comments to the .env file with some useful info

**Comment by c0sogi** [comment]
i will consider that
