### ISSUE TITLE
Are you open to a private chat

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/chatgpt-webapp-server#9]
I have an idea for company/product. I think it's winner take all situation but it requires a first mover advantage. Btw I live in Canada

**Comment by c0sogi** [comment]
I'm glad to hear that you have an idea for a company/product that could potentially benefit from the technology used in my app. If there are any specific ways we can collaborate or share knowledge, I would be open to discussing them further. However, I am busy with a lot of school projects and preparing for graduation, so I may not be able to respond quickly to issues at times.

Still I am open to any opinion. My email is cosogi@icloud.com

**Comment by Torhamilton** [comment]
I sent you an email. You can edit out your email from your last comment. thanks
